#!/bin/bash
       #--save_dir exps/pbelief_obl1f_all_colours \
python train_belief.py \
       --save_dir exps/test \
       --num_thread 24 \
       --num_game_per_thread 80 \
       --batchsize 128 \
       --lr 6.25e-05 \
       --eps 1.5e-05 \
       --grad_clip 5 \
       --hid_dim 512 \
       --burn_in_frames 10000 \
       --replay_buffer_size 100000 \
       --epoch_len 1000 \
       --num_epoch 5001 \
       --train_device cuda:0 \
       --act_device cuda:1 \
       --explore 1 \
       --policy ../training_models/obl1/model0.pthw \
       --seed 1298329 \
       --num_player 2 \
       --convention conventions/all_colours.json \
       --num_conventions 25 \
       --convention_act_override 3 \
       --parameterized 1 \

#python train_belief.py \
       #--save_dir exps/test \
       #--num_thread 24 \
       #--num_game_per_thread 80 \
       #--batchsize 128 \
       #--lr 6.25e-05 \
       #--eps 1.5e-05 \
       #--grad_clip 5 \
       #--hid_dim 512 \
       #--burn_in_frames 10000 \
       #--replay_buffer_size 100000 \
       #--epoch_len 1000 \
       #--num_epoch 5001 \
       #--train_device cuda:0 \
       #--act_device cuda:1 \
       #--explore 1 \
       #--policy ../training_models/obl1/model0.pthw \
       #--seed 1298329 \
       #--num_player 2 \
       #--convention conventions/all_colours.json \
       #--num_conventions 25 \
       #--convention_act_override 3 \
       #--parameterized 1 \
