FROM ravihammond/conda-temp

#RUN pip install torch==1.10.2+cu113 torchvision==0.11.3+cu113 torchaudio==0.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html

#RUN pip install \
#    psutil 

RUN echo "source setup_conda.bash" >> ~/.bashrc 
RUN echo 'wandb login $(cat wandb_api_key.txt)' >> ~/.bashrc

WORKDIR /app

RUN 

CMD ["python3"]
